// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://couicnykidenulcvxnsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdWljbnlraWRlbnVsY3Z4bnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDQwNzcsImV4cCI6MjA3MTA4MDA3N30.FRiusa9s8iC4yuRH-wG_BAW7an9eUo0-xcaLNafiu8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});